package com.go.sport.constants

class Constants {
    companion object {
        //region fonts
        const val BOLD = "RobotoBold.ttf"
        const val LIGHT = "RobotoLight.ttf"
        const val MEDIUM = "RobotoMedium.ttf"
        const val REGULAR = "RobotoRegular.ttf"
        //endregion

        //region api
        const val BASE_URL = "https://go-playapp.com/sports_republica/api/"
        const val LOGIN = "auth/login"
        const val SEND = "auth/send"
        const val VALIDATE_OTP = "auth/valdiateotp"
        const val SIGN_UP = "auth/signup"
        const val GET_SPORTS = "auth/get_sports"
        const val SELECT_SPORTS = "auth/select_sports"
        const val UPLOAD_USER_IMAGE = "auth/upload_user_image"
        const val PRIVACY_POLICY = "auth/privacy_policy"
        const val TERMS_AND_CONDITIONS = "auth/terms_conditions"
        const val CHANGE_PASSWORD = "auth/change_password"
        const val MY_PROFILE = "auth/my_profile"
        const val UPDATE_PROFILE = "auth/update_profile"
        const val GET_FEATURES = "auth/get_features"
        const val GET_FACILITIES = "auth/get_facilites"
        const val GET_FACILITIES_DATA = "auth/get_facility_data"
        const val GET_SLOTS = "auth/get_slot"
        const val SELECTED_SLOTS_PRICE = "auth/selected_slots_price"
        const val HOST_ACTIVITY = "auth/host_activity"
        const val BOOK_FACILITY = "auth/book_facility"
        const val LEADER_BOARD = "auth/leader_board"
        const val PLAY = "auth/play"
        const val JOIN_GAME = "auth/join_game"
        const val INVITES = "auth/list_invite"
        const val WALLET_AMOUNT = "auth/wallet_amount"
        const val WALLET_HISTORY = "auth/wallet_history"
        const val TRANSFER_WALLET = "auth/transfer_wallet"
        const val RECHARGE_WALLET = "auth/recharge_wallet"
        const val GET_USERS = "auth/get_user"
        const val USER_PROFILE = "auth/user_profile"
        const val RESPOND_INVITE = "auth/respond_invite"
        const val MY_GAMES = "auth/my_games"
        const val MY_BOOKINGS = "auth/my_bookings"
        const val FACEBOOK_SIGN_UP = "auth/facebook_signup"
        const val GOOGLE_SIGN_UP = "auth/google_signup"
        const val BOOK_Facility = "auth/book_facility"
        const val GAME_JOINS = "auth/game_joins"
        const val GAME_INVITES = "auth/game_invites"
        const val UPDATE_FCM_TOKEN = "auth/update_fcm_token"
        const val FUND_HISTORY_FILTER = "auth/fund_history_filter"
        const val GAME_FILTER = "auth/game_filter"
        const val ADVANCED_GAME_FILTER = "auth/advanced_game_filter"
        const val COMMUNITY_FILTER = "auth/community_filter"
        const val FACILITY_FILTER = "auth/facility_filter"
        const val ACADEMY_FILTER = "auth/academy_filter"
        const val GET_ACADMIES = "auth/get_acadmies"
        const val REQUEST_FUND = "auth/request_fund"
        const val RECIEVED_REQS = "auth/recieved_reqs"
        const val DELETE_RECIEVED_REQS = "auth/delete_recieved_reqs"
        const val ACCEPT_RECEIVED_REQ = "auth/accept_request_fund"
        const val LIST_UNJOINED = "auth/list_index"
        const val JOINED_GROUPS = "auth/list_group"
        const val VIEW_GROUP = "auth/view_group"
        const val CREATE_GROUP = "auth/create_group"
        const val REMOVE_GROUP_MEMBER = "auth/remove_members"
        const val ADD_GROUP_MEMBER = "auth/add_member"
        const val SEND_GROUP_NOTIFICATION = "auth/send_group_notification"
        const val SEND_USER_NOTIFICATION = "auth/send_user_notification"
        const val CONTACT_US = "auth/contact_us"
        const val GET_OFFERS = "auth/get_offer"
        const val GAMES_ONLY = "auth/games_only"
        const val CANCEL_BOOKINGS = "auth/cancel_event"
        const val PAST_GAMES = "auth/past_games"
        const val PAST_BOOKINGS = "auth/past_bookings"
        const val LEAVE_GAME = "auth/leave_game"
        const val LEAVE_GAME_PLAY = "auth/leave_game_addon"
        const val PUBLIC_GROUPS = "auth/list_public_group"
        const val REMOVE_GROUP = "auth/remove_group"
        //endregion
    }
}